### ISSUE TITLE
Automatically move on to next chapter

### ISSUE THREAD

**Issue by ronilaukkarinen** [Goodwy/PlayBook#39]
### Overview

I noticed the playback pauses each time new chapter starts. Why? Couldn't it automatically just continue? Android 13, PixelExperience.

### How to reproduce

1. Play some audiobook
2. Go running
3. Notice the playback stopping when chapter ends

### Version

2.1.0

### Android Version

33

### Device Model

KB2003

**Comment by blueclochard** [comment]
Noticed this as well since the last update. Also on Android 13.

It's a bit unfortunate that bugs like these seem to be introduced quickly, but take a long time to fix. I would prefer stable versions and do not care that much about new features. App is good enough as it is.

Sometimes I feel a bit silly that I paid for an app that is basically the same as Voice, which it is based on, but is not as stable and has a less active developer.

**Comment by Goodwy** [comment]
Fixed on version 3.0.0.
